"""枚举整合迁移

Revision ID: 5b2472955987
Revises: 4ed7a9b69552
Create Date: 2025-08-18 23:34:34.806652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b2472955987'
down_revision = '4ed7a9b69552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_index_base',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('index_code', sa.String(length=20), nullable=False, comment='指数代码，如000001.SH'),
    sa.Column('index_name', sa.String(length=255), nullable=False, comment='指数名称'),
    sa.Column('index_type', sa.Integer(), nullable=False, comment='指数类型: 0-宽基指数, 1-行业指数, 2-主题指数, 3-策略指数'),
    sa.Column('market', sa.Integer(), nullable=False, comment='所属市场: 0-中国, 1-香港, 2-美国'),
    sa.Column('base_date', sa.Date(), nullable=False, comment='基准日期'),
    sa.Column('base_point', sa.Integer(), nullable=False, comment='基准点数'),
    sa.Column('currency', sa.Integer(), server_default='0', nullable=False, comment='计价货币: 0-人民币, 1-美元, 2-欧元, 3-港币'),
    sa.Column('weight_method', sa.Integer(), nullable=True, comment='权重计算方法: 0-市值加权, 1-等权重, 2-基本面加权, 3-其他'),
    sa.Column('calculation_method', sa.Integer(), nullable=True, comment='计算方法: 0-价格加权, 1-总收益, 2-净收益, 3-其他'),
    sa.Column('status', sa.Integer(), server_default='1', nullable=False, comment='状态：0-停用，1-启用'),
    sa.Column('description', sa.Text(), nullable=True, comment='指数描述'),
    sa.Column('publisher', sa.String(length=100), nullable=True, comment='发布机构'),
    sa.Column('publish_date', sa.Date(), nullable=True, comment='发布日期'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.Column('discriminator', sa.String(length=50), server_default='base', nullable=False, comment='多态标识符'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_code'),
    comment='指数基础信息表'
    )
    op.create_table('tb_index_alias',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('index_id', sa.BigInteger(), nullable=False, comment='关联指数基础表ID'),
    sa.Column('provider_code', sa.String(length=50), nullable=False, comment='数据提供商代码，如yahoo、bloomberg、wind等'),
    sa.Column('provider_symbol', sa.String(length=100), nullable=False, comment='提供商的指数代码，如^GSPC、SPX等'),
    sa.Column('provider_name', sa.String(length=255), nullable=True, comment='提供商的指数名称'),
    sa.Column('is_primary', sa.Boolean(), server_default='0', nullable=False, comment='是否为主要代码：0-否，1-是'),
    sa.Column('status', sa.Integer(), server_default='1', nullable=False, comment='状态：0-停用，1-启用'),
    sa.Column('description', sa.Text(), nullable=True, comment='别名描述或备注'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['index_id'], ['tb_index_base.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code', 'provider_symbol', name='uk_provider_symbol'),
    comment='指数别名表，存储数据提供商代码映射'
    )
    op.create_table('tb_stock_index',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID，外键关联index_base表'),
    sa.Column('constituent_count', sa.Integer(), nullable=True, comment='成分股数量'),
    sa.Column('market_cap', sa.Float(precision=15, asdecimal=2), nullable=True, comment='总市值（万元）'),
    sa.Column('free_float_market_cap', sa.Float(precision=15, asdecimal=2), nullable=True, comment='自由流通市值（万元）'),
    sa.Column('average_pe', sa.Float(precision=10, asdecimal=2), nullable=True, comment='平均市盈率'),
    sa.Column('average_pb', sa.Float(precision=10, asdecimal=2), nullable=True, comment='平均市净率'),
    sa.Column('dividend_yield', sa.Float(precision=6, asdecimal=4), nullable=True, comment='股息率（%）'),
    sa.Column('turnover_rate', sa.Float(precision=6, asdecimal=4), nullable=True, comment='换手率（%）'),
    sa.Column('volatility', sa.Float(precision=6, asdecimal=4), nullable=True, comment='波动率（%）'),
    sa.Column('beta', sa.Float(precision=6, asdecimal=4), nullable=True, comment='贝塔系数'),
    sa.Column('rebalance_frequency', sa.String(length=20), nullable=True, comment='调仓频率：quarterly-季度，semi_annual-半年，annual-年度'),
    sa.Column('last_rebalance_date', sa.Date(), nullable=True, comment='最后调仓日期'),
    sa.Column('next_rebalance_date', sa.Date(), nullable=True, comment='下次调仓日期'),
    sa.ForeignKeyConstraint(['id'], ['tb_index_base.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='股票指数表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_stock_index')
    op.drop_table('tb_index_alias')
    op.drop_table('tb_index_base')
    # ### end Alembic commands ###
