"""Sync trade_analysis_data model changes

Revision ID: 3d2b55717c58
Revises: 7b8f16b99fc4
Create Date: 2025-11-26 22:22:44.654152

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d2b55717c58'
down_revision = '7b8f16b99fc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_trade_analysis_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annualized_return', sa.Integer(), nullable=True, comment='年化收益率（万倍）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_trade_analysis_data', schema=None) as batch_op:
        batch_op.drop_column('annualized_return')

    # ### end Alembic commands ###
