"""第三步：表重命名和创建新表

Revision ID: 679cbda7e843
Revises: step2_add_constraints
Create Date: 2025-01-26 23:42:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679cbda7e843'
down_revision = '02047ee4b143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 删除外键约束（为重命名做准备）
    op.drop_constraint('tb_grid_transaction_analysis_data_ibfk_1', 
                      'tb_grid_transaction_analysis_data', type_='foreignkey')
    
    # 2. 重命名表
    op.rename_table('tb_transaction_analysis_data', 'tb_trade_analysis_data')
    op.rename_table('tb_grid_transaction_analysis_data', 'tb_grid_trade_analysis_data')
    
    # 3. 重新创建外键约束
    op.create_foreign_key('tb_grid_trade_analysis_data_ibfk_1', 
                         'tb_grid_trade_analysis_data', 'tb_trade_analysis_data', 
                         ['id'], ['id'])
    
    # 4. 更新polymorphic_identity值
    op.execute("""
        UPDATE tb_trade_analysis_data 
        SET sub_analysis_type = 'trade_analysis' 
        WHERE sub_analysis_type = 'transaction_analysis'
    """)
    
    op.execute("""
        UPDATE tb_trade_analysis_data 
        SET sub_analysis_type = 'grid_trade_analysis' 
        WHERE sub_analysis_type = 'grid_transaction_analysis'
    """)
    
    # 5. 创建tb_amount_trade_analysis_data表
    op.create_table('tb_amount_trade_analysis_data',
        sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID，外键关联父表'),
        sa.Column('dividend_yield', sa.Integer(), nullable=True, 
                 comment='股息率（万倍，即12.34%存储为123400）'),
        sa.ForeignKeyConstraint(['id'], ['tb_trade_analysis_data.id'], 
                               name='tb_amount_trade_analysis_data_ibfk_1'),
        sa.PrimaryKeyConstraint('id'),
        comment='金额交易分析数据表，新增股息率字段'
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 删除新创建的表
    op.drop_table('tb_amount_trade_analysis_data')
    
    # 2. 回滚polymorphic_identity值
    op.execute("""
        UPDATE tb_trade_analysis_data 
        SET sub_analysis_type = 'transaction_analysis' 
        WHERE sub_analysis_type = 'trade_analysis'
    """)
    
    op.execute("""
        UPDATE tb_trade_analysis_data 
        SET sub_analysis_type = 'grid_transaction_analysis' 
        WHERE sub_analysis_type = 'grid_trade_analysis'
    """)
    
    # 3. 删除外键约束
    op.drop_constraint('tb_grid_trade_analysis_data_ibfk_1', 
                      'tb_grid_trade_analysis_data', type_='foreignkey')
    
    # 4. 重命名表回原名
    op.rename_table('tb_grid_trade_analysis_data', 'tb_grid_transaction_analysis_data')
    op.rename_table('tb_trade_analysis_data', 'tb_transaction_analysis_data')
    
    # 5. 重新创建原来的外键约束
    op.create_foreign_key('tb_grid_transaction_analysis_data_ibfk_1', 
                         'tb_grid_transaction_analysis_data', 'tb_transaction_analysis_data', 
                         ['id'], ['id'])
    
    # ### end Alembic commands ###