"""stg first migrate

Revision ID: 6ef5da7324fc
Revises: 
Create Date: 2025-06-02 12:24:05.958016

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6ef5da7324fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grid_detail', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('fund_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='对应的基金ID',
               existing_nullable=False)
        batch_op.alter_column('grid_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='网格名字',
               existing_nullable=False)
        batch_op.alter_column('fund_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='基金名字',
               existing_nullable=False)
        batch_op.alter_column('gear',
               existing_type=mysql.VARCHAR(length=255),
               comment='档位',
               existing_nullable=False)
        batch_op.alter_column('purchase_price',
               existing_type=mysql.FLOAT(),
               comment='买入价格',
               existing_nullable=False)
        batch_op.alter_column('purchase_amount',
               existing_type=mysql.FLOAT(),
               comment='买入金额',
               existing_nullable=False)
        batch_op.alter_column('purchase_shares',
               existing_type=mysql.INTEGER(display_width=11),
               comment='入股数',
               existing_nullable=False)
        batch_op.alter_column('trigger_purchase_price',
               existing_type=mysql.FLOAT(),
               comment='买入触发价',
               existing_nullable=False)
        batch_op.alter_column('trigger_sell_price',
               existing_type=mysql.FLOAT(),
               comment='卖出触发价',
               existing_nullable=False)
        batch_op.alter_column('sell_price',
               existing_type=mysql.FLOAT(),
               comment='卖出价格',
               existing_nullable=False)
        batch_op.alter_column('sell_shares',
               existing_type=mysql.INTEGER(display_width=11),
               comment='出股数',
               existing_nullable=False)
        batch_op.alter_column('actual_sell_shares',
               existing_type=mysql.INTEGER(display_width=11),
               comment='实际出股数',
               existing_nullable=False)
        batch_op.alter_column('sell_amount',
               existing_type=mysql.FLOAT(),
               comment='卖出金额',
               existing_nullable=False)
        batch_op.alter_column('profit',
               existing_type=mysql.FLOAT(),
               comment='收益',
               existing_nullable=False)
        batch_op.alter_column('save_share_profit',
               existing_type=mysql.FLOAT(),
               comment='留股收益',
               existing_nullable=False)
        batch_op.alter_column('save_share',
               existing_type=mysql.INTEGER(display_width=11),
               comment='留存股数',
               existing_nullable=False)
        batch_op.alter_column('grid_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='对应的网格ID',
               existing_nullable=False)
        batch_op.alter_column('is_current',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否处于当前档位(0否，1是)',
               existing_nullable=False)

    with op.batch_alter_table('grid_record', schema=None) as batch_op:
        batch_op.alter_column('grid_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='网格ID',
               existing_nullable=False)
        batch_op.alter_column('record_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='交易记录ID',
               existing_nullable=False)

    with op.batch_alter_table('irecord', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('trade_date',
               existing_type=mysql.DATETIME(),
               comment='交易日期',
               existing_nullable=False)
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=255),
               comment='交易代码',
               existing_nullable=False)
        batch_op.alter_column('value',
               existing_type=mysql.FLOAT(),
               comment='交易净值',
               existing_nullable=False)
        batch_op.alter_column('share',
               existing_type=mysql.INTEGER(display_width=11),
               comment='交易份额',
               existing_nullable=False)
        batch_op.alter_column('fee',
               existing_type=mysql.FLOAT(),
               comment='交易费用',
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='交易类型0：其他，1：网格',
               existing_nullable=False)
        batch_op.alter_column('notice_date',
               existing_type=mysql.DATETIME(),
               comment='通知添加时间',
               existing_nullable=True)

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('path',
               existing_type=mysql.VARCHAR(length=255),
               comment='路由地址',
               existing_nullable=False)
        batch_op.alter_column('component',
               existing_type=mysql.VARCHAR(length=255),
               comment='组件路径',
               existing_nullable=True)
        batch_op.alter_column('hidden',
               existing_type=mysql.INTEGER(display_width=11),
               comment='是否隐藏(0否，1是)',
               existing_nullable=True)
        batch_op.alter_column('redirect',
               existing_type=mysql.VARCHAR(length=255),
               comment='重定向路径',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               comment='菜单名称',
               existing_nullable=True)
        batch_op.alter_column('icon',
               existing_type=mysql.VARCHAR(length=255),
               comment='图标',
               existing_nullable=True)
        batch_op.alter_column('parent_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='父菜单id',
               existing_nullable=True)
        batch_op.alter_column('is_frame',
               existing_type=mysql.VARCHAR(length=255),
               comment='是否为外链(0否，1是)',
               existing_nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment='创建时间',
               existing_nullable=False)

    with op.batch_alter_table('stock_fund', schema=None) as batch_op:
        batch_op.alter_column('base_code',
               existing_type=mysql.VARCHAR(length=255),
               comment='基础代码',
               existing_nullable=False)
        batch_op.alter_column('xq_code',
               existing_type=mysql.VARCHAR(length=255),
               comment='雪球基金中的代码',
               existing_nullable=False)
        batch_op.alter_column('ttjj_code',
               existing_type=mysql.VARCHAR(length=255),
               comment='天天基金中的代码',
               existing_nullable=False)
        batch_op.alter_column('fund_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='股票基金名称',
               existing_nullable=False)
        batch_op.alter_column('index_code',
               existing_type=mysql.VARCHAR(length=255),
               comment='基金跟踪的指数',
               existing_nullable=True)
        batch_op.alter_column('index_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='基金跟踪的指数名称',
               existing_nullable=True)
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               comment='更新时间',
               existing_nullable=False)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment='删除时间',
               existing_nullable=False)
        batch_op.alter_column('of_code',
               existing_type=mysql.VARCHAR(length=255),
               comment='场外基金代码',
               existing_nullable=True)
        batch_op.alter_column('fund_price',
               existing_type=mysql.FLOAT(),
               comment='基金价格（从雪球API中获取）',
               existing_nullable=True)
        batch_op.alter_column('fund_value',
               existing_type=mysql.FLOAT(),
               comment='基金净值（从天天基金API中获取）',
               existing_nullable=True)
        batch_op.alter_column('fund_value_date',
               existing_type=mysql.DATETIME(),
               comment='基金净值对应的日期',
               existing_nullable=True)
        batch_op.alter_column('fund_price_date',
               existing_type=mysql.DATETIME(),
               comment='基金价格对应的日期',
               existing_nullable=True)

    with op.batch_alter_table('tb_apscheduler_log', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=mysql.VARCHAR(length=100),
               comment='任务对应的模块方法',
               existing_nullable=False)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               comment='数据创建时间',
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               comment='数据更新时间',
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('tb_asset', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=mysql.INTEGER(display_width=11),
               server_default='0',
               existing_comment='货币类型,0:人民币,1:美元',
               existing_nullable=True)
        batch_op.alter_column('asset_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='资产名称',
               existing_nullable=False)

    with op.batch_alter_table('tb_asset_category', schema=None) as batch_op:
        batch_op.alter_column('asset_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='资产ID',
               existing_comment='证券ID',
               existing_nullable=False)

    with op.batch_alter_table('tb_asset_code', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('tb_asset_fund_daily_data', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('asset_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='资产ID',
               existing_nullable=False)
        batch_op.alter_column('f_date',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment='时间')
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('tb_asset_fund_fee_rule', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.create_table_comment(
        '基金资产收费规则',
        existing_comment=None
    )

    with op.batch_alter_table('tb_asset_holding_data', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('ah_asset_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='资产名称',
               existing_comment='持仓资产名称',
               existing_nullable=False)
        batch_op.alter_column('ah_percent',
               existing_type=mysql.INTEGER(display_width=11),
               comment='涨跌幅（百分比的整数形式）',
               existing_comment='涨跌幅（千倍）',
               existing_nullable=True)
        batch_op.create_table_comment(
        '资产持仓数据',
        existing_comment=None
    )

    with op.batch_alter_table('tb_category', schema=None) as batch_op:
        batch_op.alter_column('category_name',
               existing_type=mysql.VARCHAR(length=50),
               comment=' 类别名称',
               existing_nullable=False)
        batch_op.alter_column('pid',
               existing_type=mysql.BIGINT(display_width=20),
               comment='父分类ID',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('ancestor',
               existing_type=mysql.VARCHAR(length=255),
               comment='祖先节点列表',
               existing_nullable=True)
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.create_table_comment(
        '分类',
        existing_comment=None
    )

    with op.batch_alter_table('tb_grid', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.create_table_comment(
        '网格策略表',
        existing_comment=None
    )

    with op.batch_alter_table('tb_grid_grid_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('grid_analysis_data_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='网格交易业务数据表ID',
               existing_comment='网格交易数据表ID',
               existing_nullable=False)

    with op.batch_alter_table('tb_grid_transaction_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('estimate_maximum_occupancy',
               existing_type=mysql.INTEGER(display_width=10),
               comment='预估剩余最大占用金额（单位：分）',
               existing_comment='预估剩余最大占用金额（单位：厘）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('tb_grid_type', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.create_table_comment(
        '网格类型表',
        existing_comment=None
    )

    with op.batch_alter_table('tb_grid_type_detail', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('monitor_type',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Integer(),
               existing_comment='监控类型：0-买入，1-卖出',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('tb_grid_type_grid_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('grid_analysis_data_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='网格交易数据分析表',
               existing_comment='网格交易数据分析表ID',
               existing_nullable=False)
        batch_op.alter_column('transaction_analysis_data_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='交易数据分析ID',
               existing_comment='交易分析数据ID',
               existing_nullable=False)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('tb_notification', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('business_type',
               existing_type=mysql.TINYINT(display_width=2),
               comment='通知的业务类型，0-网格交易通知,1-消息处理提醒通知,2-系统运行通知,3-日常报告通知',
               existing_comment='通知的业务类型，0-网格交易通知,1-消息处理通知,2-系统运行通知',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               comment='通知的内容',
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               comment='通知的时间',
               existing_comment='通知的时间，发送的时间',
               existing_nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_comment='数据创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               comment='更新时间',
               existing_comment='数据更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    with op.batch_alter_table('tb_notification_log', schema=None) as batch_op:
        batch_op.create_table_comment(
        '通知日志表',
        existing_comment=None
    )

    with op.batch_alter_table('tb_record', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('strategy_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='策略类型：0-网格',
               existing_nullable=True)
        batch_op.alter_column('strategy_key',
               existing_type=mysql.BIGINT(display_width=20),
               comment='策略类型对应的具体策略ID',
               existing_nullable=True)
        batch_op.create_table_comment(
        '交易记录表',
        existing_comment=None
    )

    with op.batch_alter_table('tb_task', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)

    with op.batch_alter_table('tb_task_log', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('execute_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='执行时间',
               existing_nullable=False)
        batch_op.alter_column('execute_result',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_comment='执行结果0-失败，1-成功',
               existing_nullable=False)
        batch_op.alter_column('time_consuming',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='运行耗时（单位：毫秒）',
               existing_nullable=False)
        batch_op.alter_column('remark',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               comment='备注',
               existing_nullable=False)

    with op.batch_alter_table('tb_transaction_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('record_date',
               existing_type=mysql.DATETIME(),
               comment='记录时间',
               existing_comment='记录日期',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('irr',
               existing_type=mysql.INTEGER(display_width=11),
               comment='内部收益率（万倍）',
               existing_nullable=True)
        batch_op.alter_column('attributable_share',
               existing_type=mysql.INTEGER(display_width=11),
               comment='持有份额（百倍）',
               existing_comment='持有成本（单位：分）',
               existing_nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_transaction_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('attributable_share',
               existing_type=mysql.INTEGER(display_width=11),
               comment='持有成本（单位：分）',
               existing_comment='持有份额（百倍）',
               existing_nullable=True)
        batch_op.alter_column('irr',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='内部收益率（万倍）',
               existing_nullable=True)
        batch_op.alter_column('record_date',
               existing_type=mysql.DATETIME(),
               comment='记录日期',
               existing_comment='记录时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tb_task_log', schema=None) as batch_op:
        batch_op.alter_column('remark',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='备注',
               existing_nullable=False)
        batch_op.alter_column('time_consuming',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'0'"),
               existing_comment='运行耗时（单位：毫秒）',
               existing_nullable=False)
        batch_op.alter_column('execute_result',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='执行结果0-失败，1-成功',
               existing_nullable=False)
        batch_op.alter_column('execute_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='执行时间',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tb_task', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tb_record', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='交易记录表'
    )
        batch_op.alter_column('strategy_key',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='策略类型对应的具体策略ID',
               existing_nullable=True)
        batch_op.alter_column('strategy_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='策略类型：0-网格',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tb_notification_log', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='通知日志表'
    )

    with op.batch_alter_table('tb_notification', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               comment='数据更新时间',
               existing_comment='更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               comment='数据创建时间',
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               comment='通知的时间，发送的时间',
               existing_comment='通知的时间',
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=mysql.TEXT(),
               comment=None,
               existing_comment='通知的内容',
               existing_nullable=True)
        batch_op.alter_column('business_type',
               existing_type=mysql.TINYINT(display_width=2),
               comment='通知的业务类型，0-网格交易通知,1-消息处理通知,2-系统运行通知',
               existing_comment='通知的业务类型，0-网格交易通知,1-消息处理提醒通知,2-系统运行通知,3-日常报告通知',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tb_grid_type_grid_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment=None,
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('transaction_analysis_data_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='交易分析数据ID',
               existing_comment='交易数据分析ID',
               existing_nullable=False)
        batch_op.alter_column('grid_analysis_data_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='网格交易数据分析表ID',
               existing_comment='网格交易数据分析表',
               existing_nullable=False)

    with op.batch_alter_table('tb_grid_type_detail', schema=None) as batch_op:
        batch_op.alter_column('monitor_type',
               existing_type=sa.Integer(),
               type_=mysql.TINYINT(display_width=1),
               existing_comment='监控类型：0-买入，1-卖出',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tb_grid_type', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='网格类型表'
    )
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tb_grid_transaction_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('estimate_maximum_occupancy',
               existing_type=mysql.INTEGER(display_width=10),
               comment='预估剩余最大占用金额（单位：厘）',
               existing_comment='预估剩余最大占用金额（单位：分）',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tb_grid_grid_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('grid_analysis_data_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='网格交易数据表ID',
               existing_comment='网格交易业务数据表ID',
               existing_nullable=False)

    with op.batch_alter_table('tb_grid', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='网格策略表'
    )
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tb_category', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='分类'
    )
        batch_op.alter_column('is_deleted',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否删除',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('ancestor',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='祖先节点列表',
               existing_nullable=True)
        batch_op.alter_column('pid',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='父分类ID',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('category_name',
               existing_type=mysql.VARCHAR(length=50),
               comment=None,
               existing_comment=' 类别名称',
               existing_nullable=False)

    with op.batch_alter_table('tb_asset_holding_data', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='资产持仓数据'
    )
        batch_op.alter_column('ah_percent',
               existing_type=mysql.INTEGER(display_width=11),
               comment='涨跌幅（千倍）',
               existing_comment='涨跌幅（百分比的整数形式）',
               existing_nullable=True)
        batch_op.alter_column('ah_asset_name',
               existing_type=mysql.VARCHAR(length=255),
               comment='持仓资产名称',
               existing_comment='资产名称',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tb_asset_fund_fee_rule', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='基金资产收费规则'
    )
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='更新时间',
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tb_asset_fund_daily_data', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment=None,
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('f_date',
               existing_type=mysql.DATETIME(),
               nullable=False,
               comment=None,
               existing_comment='时间')
        batch_op.alter_column('asset_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='资产ID',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tb_asset_code', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='创建时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tb_asset_category', schema=None) as batch_op:
        batch_op.alter_column('asset_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='证券ID',
               existing_comment='资产ID',
               existing_nullable=False)

    with op.batch_alter_table('tb_asset', schema=None) as batch_op:
        batch_op.alter_column('asset_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='资产名称',
               existing_nullable=False)
        batch_op.alter_column('currency',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='货币类型,0:人民币,1:美元',
               existing_nullable=True)

    with op.batch_alter_table('tb_apscheduler_log', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_comment='数据更新时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               comment='创建时间',
               existing_comment='数据创建时间',
               existing_nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('job_id',
               existing_type=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='任务对应的模块方法',
               existing_nullable=False)

    with op.batch_alter_table('stock_fund', schema=None) as batch_op:
        batch_op.alter_column('fund_price_date',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='基金价格对应的日期',
               existing_nullable=True)
        batch_op.alter_column('fund_value_date',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='基金净值对应的日期',
               existing_nullable=True)
        batch_op.alter_column('fund_value',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='基金净值（从天天基金API中获取）',
               existing_nullable=True)
        batch_op.alter_column('fund_price',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='基金价格（从雪球API中获取）',
               existing_nullable=True)
        batch_op.alter_column('of_code',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='场外基金代码',
               existing_nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               comment=None,
               existing_comment='删除时间',
               existing_nullable=False)
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               comment=None,
               existing_comment='更新时间',
               existing_nullable=False)
        batch_op.alter_column('index_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='基金跟踪的指数名称',
               existing_nullable=True)
        batch_op.alter_column('index_code',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='基金跟踪的指数',
               existing_nullable=True)
        batch_op.alter_column('fund_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='股票基金名称',
               existing_nullable=False)
        batch_op.alter_column('ttjj_code',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='天天基金中的代码',
               existing_nullable=False)
        batch_op.alter_column('xq_code',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='雪球基金中的代码',
               existing_nullable=False)
        batch_op.alter_column('base_code',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='基础代码',
               existing_nullable=False)

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               comment=None,
               existing_comment='创建时间',
               existing_nullable=False)
        batch_op.alter_column('is_frame',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='是否为外链(0否，1是)',
               existing_nullable=True)
        batch_op.alter_column('parent_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='父菜单id',
               existing_nullable=True)
        batch_op.alter_column('icon',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='图标',
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='菜单名称',
               existing_nullable=True)
        batch_op.alter_column('redirect',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='重定向路径',
               existing_nullable=True)
        batch_op.alter_column('hidden',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='是否隐藏(0否，1是)',
               existing_nullable=True)
        batch_op.alter_column('component',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='组件路径',
               existing_nullable=True)
        batch_op.alter_column('path',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='路由地址',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('irecord', schema=None) as batch_op:
        batch_op.alter_column('notice_date',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='通知添加时间',
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='交易类型0：其他，1：网格',
               existing_nullable=False)
        batch_op.alter_column('fee',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='交易费用',
               existing_nullable=False)
        batch_op.alter_column('share',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='交易份额',
               existing_nullable=False)
        batch_op.alter_column('value',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='交易净值',
               existing_nullable=False)
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='交易代码',
               existing_nullable=False)
        batch_op.alter_column('trade_date',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='交易日期',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('grid_record', schema=None) as batch_op:
        batch_op.alter_column('record_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='交易记录ID',
               existing_nullable=False)
        batch_op.alter_column('grid_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='网格ID',
               existing_nullable=False)

    with op.batch_alter_table('grid_detail', schema=None) as batch_op:
        batch_op.alter_column('is_current',
               existing_type=mysql.TINYINT(display_width=1),
               comment=None,
               existing_comment='是否处于当前档位(0否，1是)',
               existing_nullable=False)
        batch_op.alter_column('grid_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='对应的网格ID',
               existing_nullable=False)
        batch_op.alter_column('save_share',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='留存股数',
               existing_nullable=False)
        batch_op.alter_column('save_share_profit',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='留股收益',
               existing_nullable=False)
        batch_op.alter_column('profit',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='收益',
               existing_nullable=False)
        batch_op.alter_column('sell_amount',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='卖出金额',
               existing_nullable=False)
        batch_op.alter_column('actual_sell_shares',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='实际出股数',
               existing_nullable=False)
        batch_op.alter_column('sell_shares',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='出股数',
               existing_nullable=False)
        batch_op.alter_column('sell_price',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='卖出价格',
               existing_nullable=False)
        batch_op.alter_column('trigger_sell_price',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='卖出触发价',
               existing_nullable=False)
        batch_op.alter_column('trigger_purchase_price',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='买入触发价',
               existing_nullable=False)
        batch_op.alter_column('purchase_shares',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='入股数',
               existing_nullable=False)
        batch_op.alter_column('purchase_amount',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='买入金额',
               existing_nullable=False)
        batch_op.alter_column('purchase_price',
               existing_type=mysql.FLOAT(),
               comment=None,
               existing_comment='买入价格',
               existing_nullable=False)
        batch_op.alter_column('gear',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='档位',
               existing_nullable=False)
        batch_op.alter_column('fund_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='基金名字',
               existing_nullable=False)
        batch_op.alter_column('grid_name',
               existing_type=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='网格名字',
               existing_nullable=False)
        batch_op.alter_column('fund_id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='对应的基金ID',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###
