"""Update Record model

Revision ID: 0b23d505ef04
Revises: d9373dde86cc
Create Date: 2025-12-20 22:00:46.102035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0b23d505ef04'
down_revision = 'd9373dde86cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_asset_alias', schema=None) as batch_op:
        batch_op.alter_column('provider_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='提供商的名称',
               existing_comment='提供商的资产名称',
               existing_nullable=True)

    with op.batch_alter_table('tb_record', schema=None) as batch_op:
        batch_op.alter_column('transactions_direction',
               existing_type=mysql.INTEGER(display_width=11),
               comment='交易方向，0:卖出,1:买入,2:转托管入,3:转托管出,4:申购,5:赎回',
               existing_comment='交易方向，0:卖出,1:买入',
               existing_nullable=False)

    with op.batch_alter_table('tb_trade_reference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_group'))
        batch_op.drop_index(batch_op.f('idx_record'))
        batch_op.create_unique_constraint('uk_record_group', ['record_id', 'group_type', 'group_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_trade_reference', schema=None) as batch_op:
        batch_op.drop_constraint('uk_record_group', type_='unique')
        batch_op.create_index(batch_op.f('idx_record'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_group'), ['group_type', 'group_id'], unique=False)

    with op.batch_alter_table('tb_record', schema=None) as batch_op:
        batch_op.alter_column('transactions_direction',
               existing_type=mysql.INTEGER(display_width=11),
               comment='交易方向，0:卖出,1:买入',
               existing_comment='交易方向，0:卖出,1:买入,2:转托管入,3:转托管出,4:申购,5:赎回',
               existing_nullable=False)

    with op.batch_alter_table('tb_asset_alias', schema=None) as batch_op:
        batch_op.alter_column('provider_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               comment='提供商的资产名称',
               existing_comment='提供商的名称',
               existing_nullable=True)

    # ### end Alembic commands ###
