"""同步GridTradeAnalysisData模型变更

Revision ID: 51d513707b7b
Revises: 989327955f59
Create Date: 2025-08-03 17:35:13.885281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51d513707b7b'
down_revision = '989327955f59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_grid_trade_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('up_sold_percent',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='距离卖出需要上涨的数量（万倍）',
               existing_nullable=True)
        batch_op.alter_column('down_bought_percent',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='距离买入需要下跌的数量（万倍）',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_grid_trade_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('down_bought_percent',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'0'"),
               existing_comment='距离买入需要下跌的数量（万倍）',
               existing_nullable=True)
        batch_op.alter_column('up_sold_percent',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'0'"),
               existing_comment='距离卖出需要上涨的数量（万倍）',
               existing_nullable=True)

    # ### end Alembic commands ###
