"""添加基金指数关联功能

Revision ID: ee296701a7a8
Revises: 008f022f505b
Create Date: 2025-08-21 00:17:20.049115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee296701a7a8'
down_revision = '008f022f505b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_asset_fund',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键和外键，关联到asset.id，形成联合表继承关系'),
    sa.Column('fund_type', sa.String(length=32), nullable=False, comment='基金投资策略类型，如INDEX_FUND、STOCK_FUND、BOND_FUND等'),
    sa.Column('trading_mode', sa.String(length=32), nullable=False, comment='基金交易方式，如ETF、LOF、OPEN_END、CLOSED_END等'),
    sa.Column('fund_company', sa.String(length=128), nullable=True, comment='基金管理公司名称'),
    sa.Column('fund_manager', sa.String(length=128), nullable=True, comment='基金经理姓名'),
    sa.Column('establishment_date', sa.Date(), nullable=True, comment='基金成立日期'),
    sa.Column('fund_scale', sa.DECIMAL(precision=20, scale=4), nullable=True, comment='基金规模，单位：万元'),
    sa.Column('fund_status', sa.Integer(), server_default='0', nullable=False, comment='基金状态：0-正常运作，1-暂停申购/赎回，2-已清盘，3-已合并'),
    sa.Column('investment_objective', sa.Text(), nullable=True, comment='投资目标描述'),
    sa.Column('investment_strategy', sa.Text(), nullable=True, comment='投资策略描述'),
    sa.ForeignKeyConstraint(['id'], ['tb_asset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='基金资产模型 - 中间层'
    )
    op.create_table('tb_asset_etf',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键和外键，关联到asset_fund.id，形成联合表继承关系'),
    sa.Column('tracking_index_code', sa.String(length=32), nullable=True, comment='跟踪指数代码，如000300（沪深300）'),
    sa.Column('tracking_index_name', sa.String(length=128), nullable=True, comment='跟踪指数名称，如沪深300指数'),
    sa.Column('index_id', sa.BigInteger(), nullable=True, comment='关联的指数ID，外键关联到IndexBase模型'),
    sa.Column('primary_exchange', sa.String(length=16), nullable=True, comment='主要交易所：SH（上海证券交易所）、SZ（深圳证券交易所）'),
    sa.Column('dividend_frequency', sa.String(length=32), nullable=True, comment='分红频率：ANNUAL（年度）、SEMI_ANNUAL（半年度）、QUARTERLY（季度）、MONTHLY（月度）'),
    sa.Column('tracking_error', sa.DECIMAL(precision=8, scale=6), nullable=True, comment='跟踪误差，年化标准差'),
    sa.ForeignKeyConstraint(['id'], ['tb_asset_fund.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['tb_index_base.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='ETF资产模型'
    )
    op.create_table('tb_asset_lof',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键和外键，关联到asset_fund.id，形成联合表继承关系'),
    sa.Column('listing_exchange', sa.String(length=16), nullable=True, comment='上市交易所：SH（上海证券交易所）、SZ（深圳证券交易所）'),
    sa.Column('subscription_fee_rate', sa.DECIMAL(precision=8, scale=6), nullable=True, comment='申购费率'),
    sa.Column('redemption_fee_rate', sa.DECIMAL(precision=8, scale=6), nullable=True, comment='赎回费率'),
    sa.Column('nav_calculation_time', sa.Time(), nullable=True, comment='净值计算时间'),
    sa.Column('trading_suspension_info', sa.Text(), nullable=True, comment='停牌信息'),
    sa.Column('index_id', sa.BigInteger(), nullable=True, comment='关联的指数ID，外键关联到IndexBase模型，仅指数型LOF使用'),
    sa.ForeignKeyConstraint(['id'], ['tb_asset_fund.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['tb_index_base.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='LOF资产模型'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_asset_lof')
    op.drop_table('tb_asset_etf')
    op.drop_table('tb_asset_fund')
    # ### end Alembic commands ###
