"""重构为联合表继承

Revision ID: 41b9b658e05a
Revises: 0680bf732fe0
Create Date: 2025-07-12 13:45:39.802168

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '41b9b658e05a'
down_revision = '0680bf732fe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_subtype', sa.String(length=50), server_default='asset', nullable=False, comment='资产子类型，用于多态继承'))

    with op.batch_alter_table('tb_asset_exchange_fund', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.BigInteger(), nullable=False, comment='主键和外键，关联到asset.id，形成联合表继承关系'))
        batch_op.drop_constraint('tb_asset_exchange_fund_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'tb_asset', ['id'], ['id'])
        batch_op.drop_column('asset_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_asset_exchange_fund', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='主键和外键，关联到asset.id，形成一对一的继承关系'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tb_asset_exchange_fund_ibfk_1', 'tb_asset', ['asset_id'], ['id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('tb_asset', schema=None) as batch_op:
        batch_op.drop_column('asset_subtype')

    # ### end Alembic commands ###
