"""add_trade_reference_model

Revision ID: 43bf5f858a09
Revises: 43c22021be0e
Create Date: 2025-12-07 10:45:48.555121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '43bf5f858a09'
down_revision = '43c22021be0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_trade_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('irr',
               existing_type=mysql.INTEGER(display_width=11),
               comment='内部收益率（万倍，即实际值0.1234存储为1234）',
               existing_comment='内部收益率（百倍，即12.34%存储为1234）',
               existing_nullable=True)
        batch_op.alter_column('investment_yield',
               existing_type=mysql.INTEGER(display_width=11),
               comment='投资收益率（万倍，即实际值12.3456存储为123456，计算值已为百分比）',
               existing_comment='投资收益率（万倍）',
               existing_nullable=True)
        batch_op.alter_column('annualized_return',
               existing_type=mysql.INTEGER(display_width=11),
               comment='年化收益率（万倍，即实际值0.1234存储为1234）',
               existing_comment='年化收益率（万倍）',
               existing_nullable=True)
        batch_op.alter_column('turnover_rate',
               existing_type=mysql.INTEGER(display_width=11),
               comment='换手率（万倍，即实际值0.1234存储为1234）',
               existing_comment='换手率（万倍）',
               existing_nullable=True)
        batch_op.alter_column('attributable_share',
               existing_type=mysql.INTEGER(display_width=11),
               comment='持有份额（百倍，即实际值12.34存储为1234）',
               existing_comment='持有份额（百倍）',
               existing_nullable=True)
        batch_op.alter_column('net_value',
               existing_type=mysql.INTEGER(display_width=11),
               comment='当日净值（单位：毫，即1.2345元存储为12345）',
               existing_comment='当日净值（单位：毫）',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_trade_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('net_value',
               existing_type=mysql.INTEGER(display_width=11),
               comment='当日净值（单位：毫）',
               existing_comment='当日净值（单位：毫，即1.2345元存储为12345）',
               existing_nullable=True)
        batch_op.alter_column('attributable_share',
               existing_type=mysql.INTEGER(display_width=11),
               comment='持有份额（百倍）',
               existing_comment='持有份额（百倍，即实际值12.34存储为1234）',
               existing_nullable=True)
        batch_op.alter_column('turnover_rate',
               existing_type=mysql.INTEGER(display_width=11),
               comment='换手率（万倍）',
               existing_comment='换手率（万倍，即实际值0.1234存储为1234）',
               existing_nullable=True)
        batch_op.alter_column('annualized_return',
               existing_type=mysql.INTEGER(display_width=11),
               comment='年化收益率（万倍）',
               existing_comment='年化收益率（万倍，即实际值0.1234存储为1234）',
               existing_nullable=True)
        batch_op.alter_column('investment_yield',
               existing_type=mysql.INTEGER(display_width=11),
               comment='投资收益率（万倍）',
               existing_comment='投资收益率（万倍，即实际值12.3456存储为123456，计算值已为百分比）',
               existing_nullable=True)
        batch_op.alter_column('irr',
               existing_type=mysql.INTEGER(display_width=11),
               comment='内部收益率（百倍，即12.34%存储为1234）',
               existing_comment='内部收益率（万倍，即实际值0.1234存储为1234）',
               existing_nullable=True)

    # ### end Alembic commands ###
