"""update_notification_log_traceback_info_to_text

Revision ID: e77d0b0f5f9e
Revises: 3f5d97292b88
Create Date: 2025-06-24 00:27:36.385835

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e77d0b0f5f9e'
down_revision = '3f5d97292b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notification_log', schema=None) as batch_op:
        batch_op.alter_column('traceback_info',
               existing_type=mysql.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_comment='异常栈信息',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notification_log', schema=None) as batch_op:
        batch_op.alter_column('traceback_info',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=1000),
               existing_comment='异常栈信息',
               existing_nullable=True)

    # ### end Alembic commands ###
