"""修复继承关系和字段类型

Revision ID: f8957aceae8e
Revises: 41b9b658e05a
Create Date: 2025-07-13 11:32:34.663789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8957aceae8e'
down_revision = '41b9b658e05a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_asset_exchange_fund', schema=None) as batch_op:
        batch_op.drop_column('asset_id')

    with op.batch_alter_table('tb_transaction_analysis_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_analysis_type', sa.String(length=50), nullable=True, server_default='transaction_analysis', comment='分析类型，对应业务表类型，用于关系关联'))
        batch_op.add_column(sa.Column('dividend_yield', sa.Integer(), nullable=True, comment='股息率（万倍）'))

    with op.batch_alter_table('tb_grid_transaction_analysis_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_type', sa.Integer(), nullable=False, server_default='1', comment='业务类型：0-网格类型交易分析，1-网格交易分析，2-网格策略交易分析'))
        batch_op.add_column(sa.Column('grid_type_id', sa.BigInteger(), nullable=True, comment='对应的网格交易类型ID'))
        batch_op.add_column(sa.Column('grid_id', sa.BigInteger(), nullable=True, comment='对应的网格ID'))
        batch_op.drop_column('update_time')
        batch_op.drop_column('record_date')
        batch_op.drop_column('create_time')
        batch_op.drop_column('transaction_analysis_data_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_transaction_analysis_data', schema=None) as batch_op:
        batch_op.drop_column('dividend_yield')
        batch_op.drop_column('sub_analysis_type')

    with op.batch_alter_table('tb_grid_transaction_analysis_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_analysis_data_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='关联交易分表ID'))
        batch_op.add_column(sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'))
        batch_op.add_column(sa.Column('record_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='记录时间，一类交易一般来说一条只有一条数据'))
        batch_op.add_column(sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'))
        batch_op.drop_column('grid_id')
        batch_op.drop_column('grid_type_id')
        batch_op.drop_column('business_type')

    with op.batch_alter_table('tb_asset_exchange_fund', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='主键和外键，关联到asset.id，形成一对一的继承关系'))

    # ### end Alembic commands ###
