# docker-compose.yml
version: '3'
services:
  web:
    build:
      context: ../../
      dockerfile: deploy/local_docker_compose/Snow_Dockerfile
    container_name: snow
    restart: no
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=application.py
      - SNOW_APP_STATUS=dev
      - FLASK_DEBUG=False
      - pushplus=${pushplus}
      - telegram_bot=${telegram_bot}
      - chat_id=${chat_id}
      - STG_DB_PASSWORD=${STG_DB_PASSWORD}
      - STG_DB_HOST=${STG_DB_HOST}
      - STG_DB_PORT=${STG_DB_PORT}
      - STG_REDIS_HOST=${STG_REDIS_HOST}
      - STG_REDIS_PORT=${STG_REDIS_PORT}
      - STG_REDIS_PASSWORD=${STG_REDIS_PASSWORD}
      - DEV_DB_PASSWORD=${STG_DB_PASSWORD}
      - DEV_DB_HOST=${STG_DB_HOST}
      - DEV_DB_PORT=${STG_DB_PORT}
      - DEV_REDIS_HOST=${STG_REDIS_HOST}
      - DEV_REDIS_PORT=${STG_REDIS_PORT}
      - DEV_REDIS_PASSWORD=${STG_REDIS_PASSWORD}
    volumes:
      - /mnt/d/DevFiles/docker_data/snowball/logs:/app/weblogs
    networks:
      - snowball
    command: gunicorn web.application:app -c ./web/gunicorn.config.py
  jenkins:
    build:
      context: ../../
      dockerfile: deploy/local_docker_compose/Jenkins_Dockerfile
    restart: no
    container_name: jenkins
    ports:
      - 8080:8080
    environment:
      - pushplus=${pushplus}
      - telegram_bot=${telegram_bot}
      - chat_id=${chat_id}
      - STG_DB_PASSWORD=${STG_DB_PASSWORD}
      - STG_DB_HOST=${STG_DB_HOST}
      - STG_DB_PORT=${STG_DB_PORT}
      - STG_REDIS_HOST=${STG_REDIS_HOST}
      - STG_REDIS_PORT=${STG_REDIS_PORT}
      - STG_REDIS_PASSWORD=${STG_REDIS_PASSWORD}
      - DEV_DB_PASSWORD=${DEV_DB_PASSWORD}
      - DEV_DB_HOST=${DEV_DB_HOST}
      - DEV_DB_PORT=${DEV_DB_PORT}
      - DEV_REDIS_HOST=${DEV_REDIS_HOST}
      - DEV_REDIS_PORT=${DEV_REDIS_PORT}
      - DEV_REDIS_PASSWORD=${DEV_REDIS_PASSWORD}
    volumes:
      - /home/leon/docker_data/jenkins:/var/jenkins_home
      # 映射到windows目录
      # - /mnt/d/DevFiles/docker_data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - snowball # 增加网络配置
    # privileged: true # 添加这一行
    # user: root # 添加这一行
  gogs:
    image: gogs/gogs:0.11.91
    restart: no
    container_name: gogs
    ports:
      - "10022:10022"
      - "3000:3000"
    environment:
      - RUN_CROUD=true
      - SSH_PORT=10022
    volumes:
      - /home/leon/docker_data/gogs:/data
    networks:
      - snowball # 增加网络配置
  snow_view:
    container_name: nginx_snowview
    build:
      context: ../../
      dockerfile: deploy/local_docker_compose/Snowview_Dockerfile
    ports:
      - 81:81
      - 443:443
    volumes:
      - /mnt/d/DevFiles/docker_data/nginx/logs:/var/log/nginx
      - /mnt/d/DevFiles/docker_data/nginx/certs:/etc/letsencrypt
      # - /mnt/d/DevFiles/docker_data/nginx/conf.d:/etc/nginx/conf.d
      # 将nginx的html文件目录映射到子系统的文件夹中 /usr/share/nginx/html/snow_view
      - /home/leon/docker_data/snow_view:/usr/share/nginx/html/snow_view
    restart: no
    networks:
      - snowball # 增加网络配置
networks:
  snowball:
    name: snowball
    driver: bridge
