"""创建tb_asset_exchange_fund表

Revision ID: 314aa46271a8
Revises: bd0c465da9d0
Create Date: 2025-07-12 11:19:01.595216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '314aa46271a8'
down_revision = 'bd0c465da9d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_asset_exchange_fund',
    sa.Column('asset_id', sa.BigInteger(), nullable=False, comment='主键和外键，关联到asset.id，形成一对一的继承关系'),
    sa.Column('exchange_market', sa.String(length=16), nullable=False, comment="交易市场，例如'SH'(上海证券交易所)或'SZ'(深圳证券交易所)"),
    sa.Column('sub_type', sa.String(length=16), nullable=False, comment="场内细分类型，用于区分'ETF'和'LOF'"),
    sa.Column('tracking_index', sa.String(length=128), nullable=True, comment="跟踪指数，例如'沪深300指数'、'中证500指数'，对于指数型基金非常重要"),
    sa.ForeignKeyConstraint(['asset_id'], ['tb_asset.id'], ),
    sa.PrimaryKeyConstraint('asset_id'),
    comment='场内基金模型'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_asset_exchange_fund')
    # ### end Alembic commands ###
