"""add_template_key_to_notification

Revision ID: 4c4b4b7b3143
Revises: 94d0e7547547
Create Date: 2025-06-29 23:02:06.257053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4b4b7b3143'
down_revision = '94d0e7547547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_key', sa.String(length=100), nullable=True, comment='完整模板文件名（含扩展名），如：summary.txt、detailed.html、urgent.txt等'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notification', schema=None) as batch_op:
        batch_op.drop_column('template_key')

    # ### end Alembic commands ###
