"""同步dev环境迁移到test环境

Revision ID: 989327955f59
Revises: c74d79c1a6d7
Create Date: 2025-07-20 23:26:42.096621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '989327955f59'
down_revision = 'c74d79c1a6d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_trade_analysis_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('asset_id', sa.BigInteger(), nullable=True, comment='对应的资产ID，部分业务，如总计数据没有资产ID'),
    sa.Column('record_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='记录时间'),
    sa.Column('maximum_occupancy', sa.Integer(), nullable=True, comment='历史最大占用（单位：分）'),
    sa.Column('unit_cost', sa.Integer(), nullable=True, comment='单位成本（单位：毫）'),
    sa.Column('purchase_amount', sa.Integer(), nullable=True, comment='申购总额（单位：分）'),
    sa.Column('present_value', sa.Integer(), nullable=True, comment='基金现值（分）'),
    sa.Column('irr', sa.Integer(), nullable=True, comment='内部收益率（百倍，即12.34%存储为1234）'),
    sa.Column('investment_yield', sa.Integer(), nullable=True, comment='投资收益率（万倍）'),
    sa.Column('turnover_rate', sa.Integer(), nullable=True, comment='换手率（万倍）'),
    sa.Column('analysis_type', sa.Integer(), nullable=True, comment='分析类型：0-网格，1-网格类型，2-网格策略，3-按仓位分析'),
    sa.Column('attributable_share', sa.Integer(), nullable=True, comment='持有份额（百倍）'),
    sa.Column('holding_cost', sa.Integer(), nullable=True, comment='持有成本（单位：分）'),
    sa.Column('dividend', sa.Integer(), nullable=True, comment='分红与赎回（单位：分）'),
    sa.Column('profit', sa.Integer(), nullable=True, comment='收益总额（单位：分）'),
    sa.Column('net_value', sa.Integer(), nullable=True, comment='当日净值（单位：毫）'),
    sa.Column('sub_analysis_type', sa.String(length=50), nullable=True, comment='分析类型，对应业务表类型，用于关系关联'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='交易分析数据表，不包含业务'
    )
    op.create_table('tb_amount_trade_analysis_data',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID，外键关联父表'),
    sa.Column('dividend_yield', sa.Integer(), nullable=True, comment='股息率（万倍，即12.34%存储为123400）'),
    sa.ForeignKeyConstraint(['id'], ['tb_trade_analysis_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='金额交易分析数据表，新增股息率字段'
    )
    op.create_table('tb_grid_trade_analysis_data',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键和外键，关联到trade_analysis_data.id，形成联合表继承关系'),
    sa.Column('business_type', sa.Integer(), nullable=False, comment='业务类型：0-网格类型交易分析，1-网格交易分析，2-网格策略交易分析'),
    sa.Column('grid_type_id', sa.BigInteger(), nullable=True, comment='对应的网格交易类型ID'),
    sa.Column('grid_id', sa.BigInteger(), nullable=True, comment='对应的网格ID'),
    sa.Column('sell_times', sa.Integer(), server_default='0', nullable=False, comment='出售次数'),
    sa.Column('estimate_maximum_occupancy', sa.Integer(), server_default='0', nullable=False, comment='预估剩余最大占用金额（单位：分）'),
    sa.Column('holding_times', sa.Integer(), server_default='0', nullable=False, comment='待出网次数'),
    sa.Column('up_sold_percent', sa.Integer(), server_default='0', nullable=True, comment='距离卖出需要上涨的数量（万倍）'),
    sa.Column('down_bought_percent', sa.Integer(), server_default='0', nullable=True, comment='距离买入需要下跌的数量（万倍）'),
    sa.Column('dividend_yield', sa.Integer(), nullable=True, comment='股息率（万倍）'),
    sa.ForeignKeyConstraint(['id'], ['tb_trade_analysis_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='网格交易分析表'
    )
    op.drop_table('tb_transaction_analysis_data')
    op.drop_table('tb_grid_transaction_analysis_data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_grid_transaction_analysis_data',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('record_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='记录时间，一类交易一般来说一条只有一条数据'),
    sa.Column('transaction_analysis_data_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='关联交易分表ID'),
    sa.Column('sell_times', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='出售次数'),
    sa.Column('estimate_maximum_occupancy', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='预估剩余最大占用金额（单位：分）'),
    sa.Column('holding_times', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=False, comment='待出网次数'),
    sa.Column('up_sold_percent', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='距离卖出需要上涨的数量（万倍）'),
    sa.Column('down_bought_percent', mysql.INTEGER(display_width=11), server_default=sa.text("'0'"), autoincrement=False, nullable=True, comment='距离买入需要下跌的数量（万倍）'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='网格交易分析表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='网格交易分析表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_transaction_analysis_data',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('asset_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='对应的资产ID，部分业务，如总计数据没有资产ID'),
    sa.Column('record_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='记录时间'),
    sa.Column('maximum_occupancy', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='历史最大占用（单位：分）'),
    sa.Column('unit_cost', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='单位成本（单位：毫）'),
    sa.Column('purchase_amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='申购总额（单位：分）'),
    sa.Column('present_value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='基金现值（分）'),
    sa.Column('irr', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='内部收益率（万倍）'),
    sa.Column('investment_yield', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='投资收益率（万倍）'),
    sa.Column('turnover_rate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='换手率（万倍）'),
    sa.Column('analysis_type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='分析类型：0-网格，1-网格类型，2-网格策略，3-按仓位分析'),
    sa.Column('attributable_share', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='持有份额（百倍）'),
    sa.Column('holding_cost', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='持有成本（单位：分）'),
    sa.Column('dividend', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='分红与赎回（单位：分）'),
    sa.Column('profit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='收益总额（单位：分）'),
    sa.Column('net_value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='当日净值（单位：厘）'),
    sa.Column('create_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('update_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='交易分析数据表，不包含业务',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='交易分析数据表，不包含业务',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tb_grid_trade_analysis_data')
    op.drop_table('tb_amount_trade_analysis_data')
    op.drop_table('tb_trade_analysis_data')
    # ### end Alembic commands ###
