"""添加asset_code、asset_short_code和asset_status字段到tb_asset表

Revision ID: bd0c465da9d0
Revises: 4c4b4b7b3143
Create Date: 2025-07-12 09:47:40.034675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd0c465da9d0'
down_revision = '4c4b4b7b3143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('asset_code', sa.String(length=50), nullable=True, comment='资产代码'))
        batch_op.add_column(sa.Column('asset_short_code', sa.String(length=20), nullable=True, comment='资产简短代码'))
        batch_op.add_column(sa.Column('asset_status', sa.Integer(), server_default='0', nullable=False, comment='资产状态,0:活跃,1:退市'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_asset', schema=None) as batch_op:
        batch_op.drop_column('asset_status')
        batch_op.drop_column('asset_short_code')
        batch_op.drop_column('asset_code')

    # ### end Alembic commands ###
