"""重命名 index_base 表的 status 字段为 index_status

Revision ID: e98236b10fb6
Revises: 889f7e5d0628
Create Date: 2025-09-24 19:41:23.909221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e98236b10fb6'
down_revision = '889f7e5d0628'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_index_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index_status', sa.Integer(), server_default='1', nullable=False, comment='状态：0-停用，1-启用'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_index_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='状态：0-停用，1-启用'))
        batch_op.drop_column('index_status')

    # ### end Alembic commands ###
