"""第二步：添加外键约束和字段迁移

Revision ID: 02047ee4b143
Revises: step1_modify_fields
Create Date: 2025-01-26 23:41:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '02047ee4b143'
down_revision = 'd41d8cd98f00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 为tb_grid_transaction_analysis_data添加dividend_yield字段
    with op.batch_alter_table('tb_grid_transaction_analysis_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dividend_yield', sa.Integer(), 
                                     nullable=True, comment='股息率（万倍）'))
        
        # 2. 添加外键约束
        batch_op.create_foreign_key('tb_grid_transaction_analysis_data_ibfk_1', 
                                   'tb_transaction_analysis_data', ['id'], ['id'])
    
    # 3. 数据迁移：将dividend_yield从父表迁移到子表
    op.execute("""
        UPDATE tb_grid_transaction_analysis_data gtad 
        JOIN tb_transaction_analysis_data tad ON gtad.id = tad.id 
        SET gtad.dividend_yield = tad.dividend_yield 
        WHERE tad.dividend_yield IS NOT NULL
    """)
    
    # 4. 删除父表中的dividend_yield字段
    with op.batch_alter_table('tb_transaction_analysis_data', schema=None) as batch_op:
        batch_op.drop_column('dividend_yield')
        
        # 5. 修改字段注释
        batch_op.alter_column('net_value',
                             existing_type=mysql.INTEGER(display_width=11),
                             comment='当日净值（单位：毫）',
                             existing_comment='当日净值（单位：厘）',
                             existing_nullable=True)
        
        batch_op.alter_column('sub_analysis_type',
                             existing_type=mysql.VARCHAR(length=50),
                             server_default=None,
                             existing_comment='分析类型，对应业务表类型，用于关系关联',
                             existing_nullable=True)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 恢复父表中的dividend_yield字段
    with op.batch_alter_table('tb_transaction_analysis_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dividend_yield', mysql.INTEGER(display_width=11), 
                                     autoincrement=False, nullable=True, comment='股息率（万倍）'))
        
        # 恢复字段注释
        batch_op.alter_column('sub_analysis_type',
                             existing_type=mysql.VARCHAR(length=50),
                             server_default=sa.text("'transaction_analysis'"),
                             existing_comment='分析类型，对应业务表类型，用于关系关联',
                             existing_nullable=True)
        
        batch_op.alter_column('net_value',
                             existing_type=mysql.INTEGER(display_width=11),
                             comment='当日净值（单位：厘）',
                             existing_comment='当日净值（单位：毫）',
                             existing_nullable=True)
    
    # 2. 数据迁移回滚：将dividend_yield从子表迁移回父表
    op.execute("""
        UPDATE tb_transaction_analysis_data tad 
        JOIN tb_grid_transaction_analysis_data gtad ON tad.id = gtad.id 
        SET tad.dividend_yield = gtad.dividend_yield 
        WHERE gtad.dividend_yield IS NOT NULL
    """)
    
    # 3. 删除子表中的字段和约束
    with op.batch_alter_table('tb_grid_transaction_analysis_data', schema=None) as batch_op:
        batch_op.drop_constraint('tb_grid_transaction_analysis_data_ibfk_1', type_='foreignkey')
        batch_op.drop_column('dividend_yield')
    
    # ### end Alembic commands ###