"""add_template_key_to_notification

Revision ID: 6c515d6b0dd0
Revises: 14585fb3eb91
Create Date: 2025-06-29 23:02:59.288946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c515d6b0dd0'
down_revision = '14585fb3eb91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_key', sa.String(length=100), nullable=True, comment='完整模板文件名（含扩展名），如：summary.txt、detailed.html、urgent.txt等'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notification', schema=None) as batch_op:
        batch_op.drop_column('template_key')

    # ### end Alembic commands ###
