"""添加资产别名功能

Revision ID: 70d9754c5650
Revises: 2293dd4539c9
Create Date: 2025-08-21 00:28:25.533634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70d9754c5650'
down_revision = '2293dd4539c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_asset_alias',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('asset_id', sa.BigInteger(), nullable=False, comment='关联资产基础表ID'),
    sa.Column('provider_code', sa.String(length=50), nullable=False, comment='数据提供商代码，如yahoo、bloomberg、wind等'),
    sa.Column('provider_symbol', sa.String(length=100), nullable=False, comment='提供商的资产代码，如AAPL、000001.SZ等'),
    sa.Column('provider_name', sa.String(length=255), nullable=True, comment='提供商的资产名称'),
    sa.Column('is_primary', sa.Boolean(), server_default='0', nullable=False, comment='是否为主要代码：0-否，1-是'),
    sa.Column('status', sa.Integer(), server_default='1', nullable=False, comment='状态：0-停用，1-启用'),
    sa.Column('description', sa.Text(), nullable=True, comment='别名描述或备注'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['asset_id'], ['tb_asset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code', 'provider_symbol', name='uk_provider_symbol'),
    comment='资产别名表，存储数据提供商代码映射'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_asset_alias')
    # ### end Alembic commands ###
