"""同步GridTradeAnalysisData模型变更

Revision ID: 957e99fa39ba
Revises: 679cbda7e843
Create Date: 2025-08-03 17:37:36.951838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '957e99fa39ba'
down_revision = '679cbda7e843'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_grid_trade_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('business_type',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='业务类型：0-网格类型交易分析，1-网格交易分析，2-网格策略交易分析',
               existing_nullable=False)
        batch_op.alter_column('up_sold_percent',
               existing_type=mysql.INTEGER(display_width=10),
               server_default=None,
               existing_comment='距离卖出需要上涨的数量（万倍）',
               existing_nullable=True)
        batch_op.alter_column('down_bought_percent',
               existing_type=mysql.INTEGER(display_width=10),
               server_default=None,
               existing_comment='距离买入需要下跌的数量（万倍）',
               existing_nullable=True)

    with op.batch_alter_table('tb_trade_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('irr',
               existing_type=mysql.INTEGER(display_width=11),
               comment='内部收益率（百倍，即12.34%存储为1234）',
               existing_comment='内部收益率（万倍）',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_trade_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('irr',
               existing_type=mysql.INTEGER(display_width=11),
               comment='内部收益率（万倍）',
               existing_comment='内部收益率（百倍，即12.34%存储为1234）',
               existing_nullable=True)

    with op.batch_alter_table('tb_grid_trade_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('down_bought_percent',
               existing_type=mysql.INTEGER(display_width=10),
               server_default=sa.text("'0'"),
               existing_comment='距离买入需要下跌的数量（万倍）',
               existing_nullable=True)
        batch_op.alter_column('up_sold_percent',
               existing_type=mysql.INTEGER(display_width=10),
               server_default=sa.text("'0'"),
               existing_comment='距离卖出需要上涨的数量（万倍）',
               existing_nullable=True)
        batch_op.alter_column('business_type',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'1'"),
               existing_comment='业务类型：0-网格类型交易分析，1-网格交易分析，2-网格策略交易分析',
               existing_nullable=False)

    # ### end Alembic commands ###
