"""update_seystem_settings_model

Revision ID: b15c76ae445d
Revises: 6ef5da7324fc
Create Date: 2025-06-07 09:31:33.423103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15c76ae445d'
down_revision = '6ef5da7324fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID，自增'),
    sa.Column('key', sa.String(length=100), nullable=False, comment='设置项唯一标识键，如"email_smtp_host"'),
    sa.Column('value', sa.Text(), nullable=False, comment='设置项的值，支持字符串、JSON等格式'),
    sa.Column('setting_type', sa.String(length=50), nullable=False, comment='设置类型：string/int/float/bool/json/password等'),
    sa.Column('group', sa.String(length=100), nullable=True, comment='设置分组：general/email/security/notification等'),
    sa.Column('description', sa.Text(), nullable=True, comment='设置项描述，用于管理界面展示和说明'),
    sa.Column('default_value', sa.Text(), nullable=True, comment='设置项默认值，用于重置或初始化'),
    sa.Column('created_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True, comment='创建时间'),
    sa.Column('updated_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True, comment='最后更新时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
