"""第一步：修改字段和表结构

Revision ID: d41d8cd98f00
Revises: 674d60350c6f
Create Date: 2025-01-26 23:40:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd41d8cd98f00'
down_revision = '674d60350c6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 为tb_transaction_analysis_data添加字段
    with op.batch_alter_table('tb_transaction_analysis_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_analysis_type', sa.String(length=50), 
                                     nullable=True, server_default='transaction_analysis', 
                                     comment='分析类型，对应业务表类型，用于关系关联'))
        batch_op.add_column(sa.Column('dividend_yield', sa.Integer(), 
                                     nullable=True, comment='股息率（万倍）'))
    
    # 2. 修改tb_grid_transaction_analysis_data表结构
    with op.batch_alter_table('tb_grid_transaction_analysis_data', schema=None) as batch_op:
        # 添加新字段
        batch_op.add_column(sa.Column('business_type', sa.Integer(), 
                                     nullable=False, server_default='1', 
                                     comment='业务类型：0-网格类型交易分析，1-网格交易分析，2-网格策略交易分析'))
        batch_op.add_column(sa.Column('grid_type_id', sa.BigInteger(), 
                                     nullable=True, comment='对应的网格交易类型ID'))
        batch_op.add_column(sa.Column('grid_id', sa.BigInteger(), 
                                     nullable=True, comment='对应的网格ID'))
        
        # 删除不需要的字段（如果存在）
        # 注意：这些字段可能在STG环境中不存在，需要检查
        try:
            batch_op.drop_column('update_time')
        except:
            pass
        try:
            batch_op.drop_column('record_date')
        except:
            pass
        try:
            batch_op.drop_column('create_time')
        except:
            pass
        try:
            batch_op.drop_column('transaction_analysis_data_id')
        except:
            pass
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 回滚tb_grid_transaction_analysis_data表结构
    with op.batch_alter_table('tb_grid_transaction_analysis_data', schema=None) as batch_op:
        # 恢复删除的字段（如果需要）
        batch_op.add_column(sa.Column('transaction_analysis_data_id', mysql.BIGINT(display_width=20), 
                                     autoincrement=False, nullable=False, 
                                     comment='关联交易分表ID'))
        batch_op.add_column(sa.Column('create_time', mysql.DATETIME(), 
                                     server_default=sa.text('CURRENT_TIMESTAMP'), 
                                     nullable=False, comment='创建时间'))
        batch_op.add_column(sa.Column('record_date', mysql.DATETIME(), 
                                     server_default=sa.text('CURRENT_TIMESTAMP'), 
                                     nullable=False, comment='记录时间，一类交易一般来说一条只有一条数据'))
        batch_op.add_column(sa.Column('update_time', mysql.DATETIME(), 
                                     server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), 
                                     nullable=False, comment='更新时间'))
        
        # 删除新添加的字段
        batch_op.drop_column('grid_id')
        batch_op.drop_column('grid_type_id')
        batch_op.drop_column('business_type')
    
    # 回滚tb_transaction_analysis_data表
    with op.batch_alter_table('tb_transaction_analysis_data', schema=None) as batch_op:
        batch_op.drop_column('dividend_yield')
        batch_op.drop_column('sub_analysis_type')
    
    # ### end Alembic commands ###