"""表名修改：tb_stock_index -> tb_index_stock

Revision ID: e0bea86ab995
Revises: 99c64d2ea65b
Create Date: 2025-08-18 23:47:30.622536

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e0bea86ab995'
down_revision = '99c64d2ea65b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_index_stock',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID，外键关联index_base表'),
    sa.Column('constituent_count', sa.Integer(), nullable=True, comment='成分股数量'),
    sa.Column('market_cap', sa.Float(precision=15, asdecimal=2), nullable=True, comment='总市值（万元）'),
    sa.Column('free_float_market_cap', sa.Float(precision=15, asdecimal=2), nullable=True, comment='自由流通市值（万元）'),
    sa.Column('average_pe', sa.Float(precision=10, asdecimal=2), nullable=True, comment='平均市盈率'),
    sa.Column('average_pb', sa.Float(precision=10, asdecimal=2), nullable=True, comment='平均市净率'),
    sa.Column('dividend_yield', sa.Float(precision=6, asdecimal=4), nullable=True, comment='股息率（%）'),
    sa.Column('turnover_rate', sa.Float(precision=6, asdecimal=4), nullable=True, comment='换手率（%）'),
    sa.Column('volatility', sa.Float(precision=6, asdecimal=4), nullable=True, comment='波动率（%）'),
    sa.Column('beta', sa.Float(precision=6, asdecimal=4), nullable=True, comment='贝塔系数'),
    sa.Column('rebalance_frequency', sa.String(length=20), nullable=True, comment='调仓频率：quarterly-季度，semi_annual-半年，annual-年度'),
    sa.Column('last_rebalance_date', sa.Date(), nullable=True, comment='最后调仓日期'),
    sa.Column('next_rebalance_date', sa.Date(), nullable=True, comment='下次调仓日期'),
    sa.ForeignKeyConstraint(['id'], ['tb_index_base.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='股票指数表'
    )
    op.drop_table('tb_stock_index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_stock_index',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='主键ID，外键关联index_base表'),
    sa.Column('constituent_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='成分股数量'),
    sa.Column('market_cap', mysql.FLOAT(), nullable=True, comment='总市值（万元）'),
    sa.Column('free_float_market_cap', mysql.FLOAT(), nullable=True, comment='自由流通市值（万元）'),
    sa.Column('average_pe', mysql.FLOAT(), nullable=True, comment='平均市盈率'),
    sa.Column('average_pb', mysql.FLOAT(), nullable=True, comment='平均市净率'),
    sa.Column('dividend_yield', mysql.FLOAT(), nullable=True, comment='股息率（%）'),
    sa.Column('turnover_rate', mysql.FLOAT(), nullable=True, comment='换手率（%）'),
    sa.Column('volatility', mysql.FLOAT(), nullable=True, comment='波动率（%）'),
    sa.Column('beta', mysql.FLOAT(), nullable=True, comment='贝塔系数'),
    sa.Column('rebalance_frequency', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=True, comment='调仓频率：quarterly-季度，semi_annual-半年，annual-年度'),
    sa.Column('last_rebalance_date', sa.DATE(), nullable=True, comment='最后调仓日期'),
    sa.Column('next_rebalance_date', sa.DATE(), nullable=True, comment='下次调仓日期'),
    sa.ForeignKeyConstraint(['id'], ['tb_index_base.id'], name=op.f('tb_stock_index_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    comment='股票指数表',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='股票指数表',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tb_index_stock')
    # ### end Alembic commands ###
