"""first migrate

Revision ID: 08dc0aac9a87
Revises: 
Create Date: 2025-06-01 19:43:03.871312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08dc0aac9a87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)

    with op.batch_alter_table('stock_fund', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='删除时间',
               existing_nullable=False)

    with op.batch_alter_table('tb_apscheduler_log', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='数据创建时间',
               existing_nullable=False)

    with op.batch_alter_table('tb_asset', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)

    with op.batch_alter_table('tb_asset_code', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)

    with op.batch_alter_table('tb_asset_fund_daily_data', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)

    with op.batch_alter_table('tb_asset_fund_fee_rule', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)

    with op.batch_alter_table('tb_asset_holding_data', schema=None) as batch_op:
        batch_op.alter_column('ah_date',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='统计日期',
               existing_nullable=False)

    with op.batch_alter_table('tb_grid_transaction_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('record_date',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='记录时间，一类交易一般来说一条只有一条数据',
               existing_nullable=False)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)

    with op.batch_alter_table('tb_grid_type_grid_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=True)

    with op.batch_alter_table('tb_notification', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)

    with op.batch_alter_table('tb_notification_log', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='数据创建时间',
               existing_nullable=False)
        batch_op.create_table_comment(
        '通知日志表',
        existing_comment=None
    )

    with op.batch_alter_table('tb_record', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('strategy_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='策略类型：0-网格',
               existing_nullable=True)
        batch_op.alter_column('strategy_key',
               existing_type=mysql.BIGINT(display_width=20),
               comment='策略类型对应的具体策略ID',
               existing_nullable=True)
        batch_op.create_table_comment(
        '交易记录表',
        existing_comment=None
    )

    with op.batch_alter_table('tb_task', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)

    with op.batch_alter_table('tb_task_log', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('execute_time',
               existing_type=mysql.DATETIME(),
               server_default=None,
               existing_comment='执行时间',
               existing_nullable=False)
        batch_op.alter_column('execute_result',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_comment='执行结果0-失败，1-成功',
               existing_nullable=False)
        batch_op.alter_column('time_consuming',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='运行耗时（单位：毫秒）',
               existing_nullable=False)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_comment='创建时间',
               existing_nullable=False)
        batch_op.alter_column('remark',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=500),
               comment='备注',
               existing_nullable=False)

    with op.batch_alter_table('tb_transaction_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键ID',
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('record_date',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               comment='记录时间',
               existing_comment='记录日期',
               existing_nullable=False)
        batch_op.alter_column('irr',
               existing_type=mysql.INTEGER(display_width=11),
               comment='内部收益率（万倍）',
               existing_nullable=True)
        batch_op.alter_column('attributable_share',
               existing_type=mysql.INTEGER(display_width=11),
               comment='持有份额（百倍）',
               existing_comment='持有成本（单位：分）',
               existing_nullable=True)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               nullable=True,
               existing_comment='创建时间')
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_transaction_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_comment='更新时间',
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=False,
               existing_comment='创建时间')
        batch_op.alter_column('attributable_share',
               existing_type=mysql.INTEGER(display_width=11),
               comment='持有成本（单位：分）',
               existing_comment='持有份额（百倍）',
               existing_nullable=True)
        batch_op.alter_column('irr',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='内部收益率（万倍）',
               existing_nullable=True)
        batch_op.alter_column('record_date',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               comment='记录日期',
               existing_comment='记录时间',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tb_task_log', schema=None) as batch_op:
        batch_op.alter_column('remark',
               existing_type=sa.String(length=500),
               type_=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='备注',
               existing_nullable=False)
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
        batch_op.alter_column('time_consuming',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'0'"),
               existing_comment='运行耗时（单位：毫秒）',
               existing_nullable=False)
        batch_op.alter_column('execute_result',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_comment='执行结果0-失败，1-成功',
               existing_nullable=False)
        batch_op.alter_column('execute_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='执行时间',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tb_task', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
        batch_op.alter_column('update_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='更新时间',
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键ID',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tb_record', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='交易记录表'
    )
        batch_op.alter_column('strategy_key',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='策略类型对应的具体策略ID',
               existing_nullable=True)
        batch_op.alter_column('strategy_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment=None,
               existing_comment='策略类型：0-网格',
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment=None,
               existing_comment='主键',
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('tb_notification_log', schema=None) as batch_op:
        batch_op.drop_table_comment(
        existing_comment='通知日志表'
    )
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='数据创建时间',
               existing_nullable=False)

    with op.batch_alter_table('tb_notification', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)

    with op.batch_alter_table('tb_grid_type_grid_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)

    with op.batch_alter_table('tb_grid_transaction_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)
        batch_op.alter_column('record_date',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='记录时间，一类交易一般来说一条只有一条数据',
               existing_nullable=False)

    with op.batch_alter_table('tb_asset_holding_data', schema=None) as batch_op:
        batch_op.alter_column('ah_date',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='统计日期',
               existing_nullable=False)

    with op.batch_alter_table('tb_asset_fund_fee_rule', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)

    with op.batch_alter_table('tb_asset_fund_daily_data', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)

    with op.batch_alter_table('tb_asset_code', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=True)

    with op.batch_alter_table('tb_asset', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)

    with op.batch_alter_table('tb_apscheduler_log', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='数据创建时间',
               existing_nullable=False)

    with op.batch_alter_table('stock_fund', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='删除时间',
               existing_nullable=False)

    with op.batch_alter_table('menu', schema=None) as batch_op:
        batch_op.alter_column('create_time',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_comment='创建时间',
               existing_nullable=False)

    # ### end Alembic commands ###
