"""add_trade_reference_model_verify

Revision ID: 22884573bf0c
Revises: 43bf5f858a09
Create Date: 2025-12-07 10:57:04.131610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22884573bf0c'
down_revision = '43bf5f858a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_trade_reference',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('record_id', sa.BigInteger(), nullable=False, comment='交易记录ID'),
    sa.Column('group_type', sa.Integer(), nullable=False, comment='分组类型: 0-Grid, 1-Portfolio...'),
    sa.Column('group_id', sa.BigInteger(), nullable=False, comment='业务对象ID'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='通用交易关联表'
    )
    with op.batch_alter_table('tb_trade_reference', schema=None) as batch_op:
        batch_op.create_index('idx_group', ['group_type', 'group_id'], unique=False)
        batch_op.create_index('idx_record', ['record_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_trade_reference', schema=None) as batch_op:
        batch_op.drop_index('idx_record')
        batch_op.drop_index('idx_group')

    op.drop_table('tb_trade_reference')
    # ### end Alembic commands ###
