"""修改IndexBase字段nullable属性

Revision ID: 5576cdcf3211
Revises: 9c5ebcd1456e
Create Date: 2025-09-24 15:17:20.613721

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5576cdcf3211'
down_revision = '9c5ebcd1456e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_index_base', schema=None) as batch_op:
        batch_op.alter_column('base_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_comment='基准日期')
        batch_op.alter_column('base_point',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='基准点数')
        batch_op.alter_column('currency',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='计价货币: 0-人民币, 1-美元, 2-欧元, 3-港币',
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_index_base', schema=None) as batch_op:
        batch_op.alter_column('currency',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='计价货币: 0-人民币, 1-美元, 2-欧元, 3-港币',
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('base_point',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='基准点数')
        batch_op.alter_column('base_date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_comment='基准日期')

    # ### end Alembic commands ###
