"""Add template_key field to Notification model

Revision ID: 67d15a8a9cd8
Revises: dd8711649dd9
Create Date: 2025-06-29 18:34:29.666368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67d15a8a9cd8'
down_revision = 'dd8711649dd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notification', schema=None) as batch_op:
        batch_op.alter_column('template_key',
               existing_type=mysql.VARCHAR(length=100),
               comment='完整模板文件名（含扩展名），如：summary.txt、detailed.html、urgent.txt等',
               existing_comment='模板标识符，用于精确指定模板，格式：{business_type}/{scenario}/{variant}',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notification', schema=None) as batch_op:
        batch_op.alter_column('template_key',
               existing_type=mysql.VARCHAR(length=100),
               comment='模板标识符，用于精确指定模板，格式：{business_type}/{scenario}/{variant}',
               existing_comment='完整模板文件名（含扩展名），如：summary.txt、detailed.html、urgent.txt等',
               existing_nullable=True)

    # ### end Alembic commands ###
