"""创建tb_amount_trade_analysis_data表

Revision ID: 7c3a91f183ac
Revises: 6d30bad3c539
Create Date: 2025-07-20 11:24:50.701738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3a91f183ac'
down_revision = '6d30bad3c539'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_amount_trade_analysis_data',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键ID，外键关联父表'),
    sa.Column('dividend_yield', sa.Integer(), nullable=True, comment='股息率（万倍，即12.34%存储为123400）'),
    sa.ForeignKeyConstraint(['id'], ['tb_trade_analysis_data.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='金额交易分析数据表，新增股息率字段'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_amount_trade_analysis_data')
    # ### end Alembic commands ###
