"""update_trade_reference_group_type_default

Revision ID: aeda6ed6bb49
Revises: 22884573bf0c
Create Date: 2025-12-07 13:23:26.293645

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aeda6ed6bb49'
down_revision = '22884573bf0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_trade_reference', schema=None) as batch_op:
        batch_op.alter_column('group_type',
               existing_type=mysql.INTEGER(display_width=11),
               server_default='0',
               comment='分组类型: 0-其他, 1-网格',
               existing_comment='分组类型: 0-Grid, 1-Portfolio...',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_trade_reference', schema=None) as batch_op:
        batch_op.alter_column('group_type',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               comment='分组类型: 0-Grid, 1-Portfolio...',
               existing_comment='分组类型: 0-其他, 1-网格',
               existing_nullable=False)

    # ### end Alembic commands ###
