"""将dividend_yield字段从TransactionAnalysisData移动到GridTransactionAnalysisData

Revision ID: d5473a55937d
Revises: f8957aceae8e
Create Date: 2025-07-19 18:51:22.762575

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5473a55937d'
down_revision = 'f8957aceae8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_grid_transaction_analysis_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dividend_yield', sa.Integer(), nullable=True, comment='股息率（万倍）'))
        batch_op.alter_column('business_type',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=None,
               existing_comment='业务类型：0-网格类型交易分析，1-网格交易分析，2-网格策略交易分析',
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'tb_transaction_analysis_data', ['id'], ['id'])

    with op.batch_alter_table('tb_transaction_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('net_value',
               existing_type=mysql.INTEGER(display_width=11),
               comment='当日净值（单位：毫）',
               existing_comment='当日净值（单位：厘）',
               existing_nullable=True)
        batch_op.alter_column('sub_analysis_type',
               existing_type=mysql.VARCHAR(length=50),
               server_default=None,
               existing_comment='分析类型，对应业务表类型，用于关系关联',
               existing_nullable=True)
        batch_op.drop_column('dividend_yield')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_transaction_analysis_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dividend_yield', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='股息率（万倍）'))
        batch_op.alter_column('sub_analysis_type',
               existing_type=mysql.VARCHAR(length=50),
               server_default=sa.text("'transaction_analysis'"),
               existing_comment='分析类型，对应业务表类型，用于关系关联',
               existing_nullable=True)
        batch_op.alter_column('net_value',
               existing_type=mysql.INTEGER(display_width=11),
               comment='当日净值（单位：厘）',
               existing_comment='当日净值（单位：毫）',
               existing_nullable=True)

    with op.batch_alter_table('tb_grid_transaction_analysis_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('business_type',
               existing_type=mysql.INTEGER(display_width=11),
               server_default=sa.text("'1'"),
               existing_comment='业务类型：0-网格类型交易分析，1-网格交易分析，2-网格策略交易分析',
               existing_nullable=False)
        batch_op.drop_column('dividend_yield')

    # ### end Alembic commands ###
