"""add_template_key_to_notification

Revision ID: dd8711649dd9
Revises: e6283c8f40ae
Create Date: 2025-06-29 17:48:53.536438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd8711649dd9'
down_revision = 'e6283c8f40ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('template_key', sa.String(length=100), nullable=True, comment='模板标识符，用于精确指定模板，格式：{business_type}/{scenario}/{variant}'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notification', schema=None) as batch_op:
        batch_op.drop_column('template_key')

    # ### end Alembic commands ###
