"""update_notification_model

Revision ID: e6283c8f40ae
Revises: 167b29892f80
Create Date: 2025-06-27 14:19:44.132629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e6283c8f40ae'
down_revision = '167b29892f80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notification', schema=None) as batch_op:
        batch_op.alter_column('notice_status',
               existing_type=mysql.TINYINT(display_width=2),
               comment='通知的状态：0-未发送，1-未读，2-已读，3-已处理，4-已发送',
               existing_comment='通知的状态：0-未发送，1-未读，2-已读，3-已处理',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notification', schema=None) as batch_op:
        batch_op.alter_column('notice_status',
               existing_type=mysql.TINYINT(display_width=2),
               comment='通知的状态：0-未发送，1-未读，2-已读，3-已处理',
               existing_comment='通知的状态：0-未发送，1-未读，2-已读，3-已处理，4-已发送',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
