server { 
    listen 81; 
    server_name localhost; 
    root /usr/share/nginx/html/snow_view; 
    index index.html index.htm;

    location / {
        try_files $uri $uri/ snow_view/index.html;
    }

    location /dev/ {
        proxy_pass http://snow:5001/;
    }
}