"""添加index模型的investment_strategy字段和更新IndexTypeEnum

Revision ID: 7b8f16b99fc4
Revises: 61ba63e90514
Create Date: 2025-09-24 21:54:49.127509

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7b8f16b99fc4'
down_revision = '61ba63e90514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_index_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investment_strategy', sa.Integer(), nullable=True, comment='投资策略: 0-宽基指数, 1-行业指数, 2-主题指数, 3-策略指数'))
        batch_op.alter_column('index_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='指数类型（底层资产类型）: 0-股票指数, 1-债券指数, 2-商品指数, 3-货币指数, 4-混合指数, 5-其他',
               existing_comment='指数类型: 0-宽基指数, 1-行业指数, 2-主题指数, 3-策略指数',
               existing_nullable=False)
        batch_op.alter_column('market',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               comment='所在市场: 0-中国, 1-香港, 2-美国',
               existing_comment='所属市场: 0-中国, 1-香港, 2-美国')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_index_base', schema=None) as batch_op:
        batch_op.alter_column('market',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               comment='所属市场: 0-中国, 1-香港, 2-美国',
               existing_comment='所在市场: 0-中国, 1-香港, 2-美国')
        batch_op.alter_column('index_type',
               existing_type=mysql.INTEGER(display_width=11),
               comment='指数类型: 0-宽基指数, 1-行业指数, 2-主题指数, 3-策略指数',
               existing_comment='指数类型（底层资产类型）: 0-股票指数, 1-债券指数, 2-商品指数, 3-货币指数, 4-混合指数, 5-其他',
               existing_nullable=False)
        batch_op.drop_column('investment_strategy')

    # ### end Alembic commands ###
