"""update notification model comments

Revision ID: 167b29892f80
Revises: e77d0b0f5f9e
Create Date: 2025-06-25 22:28:52.521210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '167b29892f80'
down_revision = 'e77d0b0f5f9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notification', schema=None) as batch_op:
        batch_op.alter_column('notice_type',
               existing_type=mysql.TINYINT(display_width=2),
               comment='通知的类型，0-消息型通知，1-确认型通知',
               existing_comment='通知的业务类型，0-网格交易通知,1-消息处理提醒通知,2-系统运行通知,3-日常报告通知',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_notification', schema=None) as batch_op:
        batch_op.alter_column('notice_type',
               existing_type=mysql.TINYINT(display_width=2),
               comment='通知的业务类型，0-网格交易通知,1-消息处理提醒通知,2-系统运行通知,3-日常报告通知',
               existing_comment='通知的类型，0-消息型通知，1-确认型通知',
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
