"""重命名表：tb_transaction_analysis_data -> tb_trade_analysis_data, tb_grid_transaction_analysis_data -> tb_grid_trade_analysis_data

Revision ID: 1dcbb2edf6db
Revises: d5473a55937d
Create Date: 2025-07-19 20:37:37.709950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1dcbb2edf6db'
down_revision = 'd5473a55937d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 重命名表而不是删除和创建，以保留数据
    
    # 1. 首先删除外键约束
    op.drop_constraint('tb_grid_transaction_analysis_data_ibfk_1', 'tb_grid_transaction_analysis_data', type_='foreignkey')
    
    # 2. 重命名主表
    op.rename_table('tb_transaction_analysis_data', 'tb_trade_analysis_data')
    
    # 3. 重命名子表
    op.rename_table('tb_grid_transaction_analysis_data', 'tb_grid_trade_analysis_data')
    
    # 4. 重新创建外键约束，指向新的表名
    op.create_foreign_key(None, 'tb_grid_trade_analysis_data', 'tb_trade_analysis_data', ['id'], ['id'])
    
    # 5. 更新 polymorphic_identity 值
    op.execute("UPDATE tb_trade_analysis_data SET sub_analysis_type = 'trade_analysis' WHERE sub_analysis_type = 'transaction_analysis'")
    op.execute("UPDATE tb_trade_analysis_data SET sub_analysis_type = 'grid_trade_analysis' WHERE sub_analysis_type = 'grid_transaction_analysis'")
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 回滚重命名操作
    
    # 1. 首先删除外键约束
    op.drop_constraint(None, 'tb_grid_trade_analysis_data', type_='foreignkey')
    
    # 2. 回滚 polymorphic_identity 值
    op.execute("UPDATE tb_trade_analysis_data SET sub_analysis_type = 'transaction_analysis' WHERE sub_analysis_type = 'trade_analysis'")
    op.execute("UPDATE tb_trade_analysis_data SET sub_analysis_type = 'grid_transaction_analysis' WHERE sub_analysis_type = 'grid_trade_analysis'")
    
    # 3. 重命名子表回原名
    op.rename_table('tb_grid_trade_analysis_data', 'tb_grid_transaction_analysis_data')
    
    # 4. 重命名主表回原名
    op.rename_table('tb_trade_analysis_data', 'tb_transaction_analysis_data')
    
    # 5. 重新创建外键约束，指向原来的表名
    op.create_foreign_key('tb_grid_transaction_analysis_data_ibfk_1', 'tb_grid_transaction_analysis_data', 'tb_transaction_analysis_data', ['id'], ['id'])
    
    # ### end Alembic commands ###
