"""重命名 index_base 表的 status 字段为 index_status

Revision ID: 2d0a239fa54a
Revises: 5576cdcf3211
Create Date: 2025-09-24 19:42:54.211457

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2d0a239fa54a'
down_revision = '5576cdcf3211'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_index_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('index_status', sa.Integer(), server_default='1', nullable=False, comment='状态：0-停用，1-启用'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_index_base', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', mysql.INTEGER(display_width=11), server_default=sa.text("'1'"), autoincrement=False, nullable=False, comment='状态：0-停用，1-启用'))
        batch_op.drop_column('index_status')

    # ### end Alembic commands ###
