"""add annualized_return to trade_analysis_data

Revision ID: 43c22021be0e
Revises: f1562e274c1e
Create Date: 2025-11-26 22:08:26.606417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43c22021be0e'
down_revision = 'f1562e274c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_trade_analysis_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('annualized_return', sa.Integer(), nullable=True, comment='年化收益率（万倍）'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_trade_analysis_data', schema=None) as batch_op:
        batch_op.drop_column('annualized_return')

    # ### end Alembic commands ###
