"""检查模型变更

Revision ID: 6d30bad3c539
Revises: 1dcbb2edf6db
Create Date: 2025-07-20 11:13:27.763776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d30bad3c539'
down_revision = '1dcbb2edf6db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_grid_trade_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键和外键，关联到trade_analysis_data.id，形成联合表继承关系',
               existing_comment='主键和外键，关联到transaction_analysis_data.id，形成联合表继承关系',
               existing_nullable=False)

    with op.batch_alter_table('tb_trade_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('irr',
               existing_type=mysql.INTEGER(display_width=11),
               comment='内部收益率（百倍，即12.34%存储为1234）',
               existing_comment='内部收益率（万倍）',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_trade_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('irr',
               existing_type=mysql.INTEGER(display_width=11),
               comment='内部收益率（万倍）',
               existing_comment='内部收益率（百倍，即12.34%存储为1234）',
               existing_nullable=True)

    with op.batch_alter_table('tb_grid_trade_analysis_data', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.BIGINT(display_width=20),
               comment='主键和外键，关联到transaction_analysis_data.id，形成联合表继承关系',
               existing_comment='主键和外键，关联到trade_analysis_data.id，形成联合表继承关系',
               existing_nullable=False)

    # ### end Alembic commands ###
