"""重命名AssetETF为AssetFundETF，AssetLOF为AssetFundLOF，更新表名和polymorphic_identity

Revision ID: 9c5ebcd1456e
Revises: 031f14a770ba
Create Date: 2025-09-03 18:32:09.631936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c5ebcd1456e'
down_revision = '031f14a770ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 首先更新polymorphic_identity值
    op.execute("UPDATE tb_asset SET asset_subtype = 'fund_etf' WHERE asset_subtype = 'etf'")
    op.execute("UPDATE tb_asset SET asset_subtype = 'fund_lof' WHERE asset_subtype = 'lof'")
    op.create_table('tb_asset_fund_etf',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键和外键，关联到asset_fund.id，形成联合表继承关系'),
    sa.Column('tracking_index_code', sa.String(length=32), nullable=True, comment='跟踪指数代码，如000300（沪深300）'),
    sa.Column('tracking_index_name', sa.String(length=128), nullable=True, comment='跟踪指数名称，如沪深300指数'),
    sa.Column('index_id', sa.BigInteger(), nullable=True, comment='关联的指数ID，外键关联到IndexBase模型'),
    sa.Column('primary_exchange', sa.String(length=16), nullable=True, comment='主要交易所：SH（上海证券交易所）、SZ（深圳证券交易所）'),
    sa.Column('dividend_frequency', sa.String(length=32), nullable=True, comment='分红频率：ANNUAL（年度）、SEMI_ANNUAL（半年度）、QUARTERLY（季度）、MONTHLY（月度）'),
    sa.Column('tracking_error', sa.DECIMAL(precision=8, scale=6), nullable=True, comment='跟踪误差，年化标准差'),
    sa.ForeignKeyConstraint(['id'], ['tb_asset_fund.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['tb_index_base.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='ETF基金资产模型'
    )
    op.create_table('tb_asset_fund_lof',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键和外键，关联到asset_fund.id，形成联合表继承关系'),
    sa.Column('listing_exchange', sa.String(length=16), nullable=True, comment='上市交易所：SH（上海证券交易所）、SZ（深圳证券交易所）'),
    sa.Column('subscription_fee_rate', sa.DECIMAL(precision=8, scale=6), nullable=True, comment='申购费率'),
    sa.Column('redemption_fee_rate', sa.DECIMAL(precision=8, scale=6), nullable=True, comment='赎回费率'),
    sa.Column('nav_calculation_time', sa.Time(), nullable=True, comment='净值计算时间'),
    sa.Column('trading_suspension_info', sa.Text(), nullable=True, comment='停牌信息'),
    sa.Column('index_id', sa.BigInteger(), nullable=True, comment='关联的指数ID，外键关联到IndexBase模型，仅指数型LOF使用'),
    sa.ForeignKeyConstraint(['id'], ['tb_asset_fund.id'], ),
    sa.ForeignKeyConstraint(['index_id'], ['tb_index_base.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='LOF基金资产模型'
    )
    op.drop_table('tb_asset_etf')
    op.drop_table('tb_asset_lof')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 首先恢复polymorphic_identity值
    op.execute("UPDATE tb_asset SET asset_subtype = 'etf' WHERE asset_subtype = 'fund_etf'")
    op.execute("UPDATE tb_asset SET asset_subtype = 'lof' WHERE asset_subtype = 'fund_lof'")
    op.create_table('tb_asset_lof',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='主键和外键，关联到asset_fund.id，形成联合表继承关系'),
    sa.Column('listing_exchange', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), nullable=True, comment='上市交易所：SH（上海证券交易所）、SZ（深圳证券交易所）'),
    sa.Column('subscription_fee_rate', mysql.DECIMAL(precision=8, scale=6), nullable=True, comment='申购费率'),
    sa.Column('redemption_fee_rate', mysql.DECIMAL(precision=8, scale=6), nullable=True, comment='赎回费率'),
    sa.Column('nav_calculation_time', mysql.TIME(), nullable=True, comment='净值计算时间'),
    sa.Column('trading_suspension_info', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True, comment='停牌信息'),
    sa.Column('index_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='关联的指数ID，外键关联到IndexBase模型，仅指数型LOF使用'),
    sa.ForeignKeyConstraint(['id'], ['tb_asset_fund.id'], name=op.f('tb_asset_lof_ibfk_1')),
    sa.ForeignKeyConstraint(['index_id'], ['tb_index_base.id'], name=op.f('tb_asset_lof_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    comment='LOF资产模型',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='LOF资产模型',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_asset_etf',
    sa.Column('id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False, comment='主键和外键，关联到asset_fund.id，形成联合表继承关系'),
    sa.Column('tracking_index_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True, comment='跟踪指数代码，如000300（沪深300）'),
    sa.Column('tracking_index_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=True, comment='跟踪指数名称，如沪深300指数'),
    sa.Column('index_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True, comment='关联的指数ID，外键关联到IndexBase模型'),
    sa.Column('primary_exchange', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=16), nullable=True, comment='主要交易所：SH（上海证券交易所）、SZ（深圳证券交易所）'),
    sa.Column('dividend_frequency', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=32), nullable=True, comment='分红频率：ANNUAL（年度）、SEMI_ANNUAL（半年度）、QUARTERLY（季度）、MONTHLY（月度）'),
    sa.Column('tracking_error', mysql.DECIMAL(precision=8, scale=6), nullable=True, comment='跟踪误差，年化标准差'),
    sa.ForeignKeyConstraint(['id'], ['tb_asset_fund.id'], name=op.f('tb_asset_etf_ibfk_1')),
    sa.ForeignKeyConstraint(['index_id'], ['tb_index_base.id'], name=op.f('tb_asset_etf_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    comment='ETF资产模型',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_comment='ETF资产模型',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('tb_asset_fund_lof')
    op.drop_table('tb_asset_fund_etf')
    # ### end Alembic commands ###
